In [41]:
import numpy as np

1. Create an array that starts from the integer 1, ends at 20, incremented by 3

In [42]:
#1
# array from 1 to 20, incremented by 3.

print(np.arange(1, 20, 3))

[ 1  4  7 10 13 16 19]


<hr style="height: 3px; background-color: black;">

2. Create a new array of shape 3 with random numbers between 0 and 1.

In [43]:
#2
# array of shape 3 with random numbers between 0 and 1

print(np.random.rand(3))

[0.96085476 0.74660245 0.53935843]


<hr style="height: 3px; background-color: black;">

3. Create a 2 D array [[10,20,45],[30,12,16],[42,17,56]] and perform the following operations:<br>
    o Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [44]:
#3
arr = np.array(
    [[10,20,45],
    [30,12,16],
    [42,17,56]]
)

rows = arr.shape[0]

# get first two rows
initial = arr[:2]

# get last two rows
last = arr[rows-2:]

print(f"The first two rows are: {initial}\n")
print(f"The last two rows are: {last}")


The first two rows are: [[10 20 45]
 [30 12 16]]

The last two rows are: [[30 12 16]
 [42 17 56]]


<hr style="height: 3px; background-color: black;">

4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, 
and split the arrays into smaller arrays.

In [45]:
#4
arr1 = np.random.randint(0, 10, size=(2,2))
arr2 = np.random.randint(0, 10, size=(2,2))

print(f"arr1: \n{arr1}\n\narr2: \n{arr2}\n")

ver_stack = np.vstack((arr1, arr2))
hor_stack = np.hstack((arr1, arr2))

print(f"Vertical Stack is \n{ver_stack}\n")
print(f"Horizontal Stack is \n{hor_stack}\n")

ver_split = np.vsplit(ver_stack, 2)
hor_split = np.hsplit(hor_stack, 2)

print(ver_split)
print()
print(hor_split)

arr1: 
[[2 3]
 [5 3]]

arr2: 
[[3 3]
 [8 5]]

Vertical Stack is 
[[2 3]
 [5 3]
 [3 3]
 [8 5]]

Horizontal Stack is 
[[2 3 3 3]
 [5 3 8 5]]

[array([[2, 3],
       [5, 3]]), array([[3, 3],
       [8, 5]])]

[array([[2, 3],
       [5, 3]]), array([[3, 3],
       [8, 5]])]


<hr style="height: 3px; background-color: black;">

5. Create two matrices 𝑋 = ([[5, 7, 2],[4, 5, 6],[7, 4 ,2]]), 𝑌 = ([[4, 2],[6, 2],[4, 2]])<br>
    o Is it possible to multiply these matrices?<br>
    o Demonstrate the case when it is not possible to.

In [46]:
#5

#a
def dot_prod(a, b):
    m1, n1 = a.shape
    m2, n2 = b.shape

    if n1==m2:
        print("Multiplication possible")
        return np.dot(x,y)
    else:
        return "Failed"

x =  np.array([[5, 7, 2],[4, 5, 6],[7, 4 ,2]])
y =  np.array([[4, 2],[6, 2],[4, 2]])

print(dot_prod(x, y))

#b
print()
a = np.array([[5, 7, 2],[4, 5, 6],[7, 4 ,2]])
b = np.array([[4, 2]])

print(dot_prod(a, b))

Multiplication possible
[[70 28]
 [70 30]
 [60 26]]

Failed


<hr style="height: 3px; background-color: black;">
6. Create two arrays, 𝑥 = ([2, −1, −8]), 𝑦 = ([3, 1, −2])<br>
o Find the Shape, Number of dimensions of vector x.<br>
o Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions 
after reshaping y to a matrix of (3,1).

In [47]:
#6
#a
x = np.array([2, -1, -8])
y = np.array([3, 1, -2]) 

print(f"Shape of x is: {x.shape}\n")
print(f"Dimensions of x is: {x.ndim}\n")
print(f"x after reshape is: \n{x.reshape(3,1)}\n")

#b
y = y.reshape(3,1)
print(f"Matrix y: \n{y}")
print(f"Dimensions of y after reshape: {y.ndim}")

Shape of x is: (3,)

Dimensions of x is: 1

x after reshape is: 
[[ 2]
 [-1]
 [-8]]

Matrix y: 
[[ 3]
 [ 1]
 [-2]]
Dimensions of y after reshape: 2


<hr style="height: 3px; background-color: black;">
7. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 
matrix.

Broadcasting is the concept in which when we have 2 matrices of different shapes, we pretend that the smaller size matrix is the same as teh bigger one by repeating its values. It's similar to copying the smaller matrix to fit the size of the bigger one. It allows us to do the mathematical operation even when the matrices are of different sizes.

In [48]:
# Shape (3, 3)
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Shape (3, 1)
B = np.array([[2],
              [2],
              [2]])

# Subtraction
sub_result = A - B
print(f"Subtraction: \n{sub_result}\n")

# Multiplication
mutliply_result = A * B
print(f"Multiplication: \n{mutliply_result}")


Subtraction: 
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

Multiplication: 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In the above examples, 'A' matrix is of size 3x3, 'B' matrix is of size 3x1. Mathematically subtraction is only possible when the shape of the matrices is same, but with the help of numpy, we can perform subtraction as well as multiplication for the above.

<hr style="height: 3px; background-color: black;">

## Part B- Linear Equations

In [49]:
def check_singular(eqn):
    # Calculating Determinant
    det_eqn = np.linalg.det(eqn)
    
    print(f"{eqn}\n")

    # Checking for singularity
    if det_eqn == 0:
        print(f"Determinant is {det_eqn}, System is singular.")
    else:
        print(f"Determinant is {det_eqn}, System is non-singular.")

### B.1

1. 4x + y - 2z = 10
2. 2x - 3y + 2z = -4
3. x + 2y + 3z = 6

In [50]:
eqn_1 = np.array([[4, 1, -2],
                  [2, -3, 2],
                  [1, 2, 3]])

check_singular(eqn_1)

[[ 4  1 -2]
 [ 2 -3  2]
 [ 1  2  3]]

Determinant is -70.00000000000003, System is non-singular.


<hr style="height: 3px; background-color: black;">

### B.2
1. 2x - y + 3z + 4w = 10
2. 4x - 2y + 6z + 8w = 20
3. 3x + y - 2z + 2w = 3
4. x + 3y - 4z + w = -1


In [51]:
eqn_2 = np.array([[2, -1, 3, 4],
                  [4, -2, 6, 8],
                  [3, 1, -2, 2],
                  [1, 3, -4, 1]])

check_singular(eqn_2)

[[ 2 -1  3  4]
 [ 4 -2  6  8]
 [ 3  1 -2  2]
 [ 1  3 -4  1]]

Determinant is 0.0, System is singular.


<hr style="height: 3px; background-color: black;">